### PR TITLE
Improving Notes Card UI 

### PR DESCRIPTION
**Pull request by Lavanyaaa25**
## Description

>Improved the UI of Notes card.

## Screenshots
Screenshot 2024-05-12 134042

### CODE REVIEW

**Comment by hereisSwapnil** [comment]
@Lavanyaaa25 I think likes should be visible as it gives a clear view about trending/most liked notes (before even opening the notes)

**Comment by Lavanyaaa25** [comment]
Yeah, will add

**Comment by Lavanyaaa25** [comment]
Done

**Comment by Lavanyaaa25** [comment]
Done
Screenshot 2024-05-12 191608

**Comment by hereisSwapnil** [comment]
@Lavanyaaa25 Please add back the .env.dev from the client and server folder

**Comment by Lavanyaaa25** [comment]
> Owner

Done

**Pull request closed without merging**
