### PR TITLE
Fix: the Fluctuating issue of Signup Form in Username Field.

### PR DESCRIPTION
**Pull request by mukulpythondev**
## Description

> Implemented a fix to prevent continuous form height fluctuation while typing in the username field on the signup form.

## Checklist

> Before submitting this pull request, kindly verify that the ensuing checkpoints have been reached.

- [x] Have you adhered to the repository's defined coding convention rules?
- [ ] Have you updated the 'documentation.md' file with the method/function documentation?
- [x] Have you sent a message along with the result or response?
- [ ] Have you used the try-catch technique?
- [ ] Has the method/class been added to the documentation (md file)?

## Screenshots

https://github.com/hereisSwapnil/ExamTime/assets/134795697/a7ad3ed5-d806-48c9-8c7d-54c270d60f1f

## Additional Notes/Comments

> This pull request addresses the issue of form height fluctuation on the signup page (#93). I've implemented a fix to ensure that the form height remains stable while the user types in the username field. 

I certify that I have carried out the relevant checks and provided the requisite screenshot for validation by submitting this pull request.
I appreciate your contribution.

### CODE REVIEW

**Comment by hereisSwapnil** [comment]
@mukulpythondev Please fix conflicts

**Comment by mukulpythondev** [comment]
Solve the Merge Conflicts Sir @hereisSwapnil  !

**Comment by hereisSwapnil** [comment]
@mukulpythondev Why have to user useEffect to show toasts and also conflicts are coming now

**Comment by mukulpythondev** [comment]
@hereisSwapnil I did not use useEffect for any toast. i simply work on the signup form username field and useEffect and other stuff come from the main branch. Now i fix all the conflcts. please merge my pr first because you everytime accept another pr that's why my branch have merge conflicts.

**Pull request merged**
