### PR TITLE
Updated Readme

### PR DESCRIPTION
**Pull request by CS251000**
## Description

> The changes made in this pull request should be briefly described.
Added a header for GSSOC and added a table of contents

## Checklist

> Before submitting this pull request, kindly verify that the ensuing checkpoints have been reached.

- [ ] Have you adhered to the repository's defined coding convention rules?
- [ ] Have you updated the 'documentation.md' file with the method/function documentation?
- [ ] Have you sent a message along with the result or response?
- [ ] Have you used the try-catch technique?
- [ ] Has the method/class been added to the documentation (md file)?

## Screenshots

> Uploading a screenshot illustrating the approach you developed for validation is required.

## Additional Notes/Comments

> Any additional remarks or suggestions concerning this pull request are welcome.

---

I certify that I have carried out the relevant checks and provided the requisite screenshot for validation by submitting this pull request.
I appreciate your contribution.

### CODE REVIEW

**Comment by hereisSwapnil** [comment]
@CS251000 Why this color change?
image

Please fix

**Comment by CS251000** [comment]
@hereisSwapnil these color changes were not done by me it was like this when i started working

I only added the heder of gssoc and the table of contents

**Comment by hereisSwapnil** [comment]
@CS251000 Please fix this also

**Comment by CS251000** [comment]
@hereisSwapnil what do i fix in this? I dont know how it looked earlier??

**Pull request merged**
