### PR TITLE
Feat: Add a Feature to Share Notes via Shareable Links

### PR DESCRIPTION
**Pull request by DonaldReddy**
## Description

This Feature brings the functionality of sharing the notes via shareable links. This feature improves the user experience by letting users share notes. It even enhances the user reach.

copyurl

I've implemented this feature so that users can share the notes via links and need to be logged in to download, like, or bookmark them. I even hid the navbar from not showing to unauthenticated users as it contains user information.

nologin

This is how users who are logged in see it.

login

## Resolves: [Issue Number]

fixes: #201 

## Checklist

> Before submitting this pull request, kindly verify that the ensuing checkpoints have been reached.

- [x] Have you adhered to the repository's defined coding convention rules?
- [x] Have you updated the 'documentation.md' file with the method/function documentation?
- [x] Have you sent a message along with the result or response?
- [x] Have you used the try-catch technique?
- [x] Has the method/class been added to the documentation (md file)?

---

I certify that I have carried out the relevant checks and provided the requisite screenshot for validation by submitting this pull request.
I appreciate your contribution.

### CODE REVIEW

**Comment by DonaldReddy** [comment]
@hereisSwapnil please review this PR.

**Comment by hereisSwapnil** [comment]
Please Resolve conflicts

**Comment by DonaldReddy** [comment]
@hereisSwapnil please review this PR

**Comment by DonaldReddy** [comment]
@hereisSwapnil please review this PR.

**Pull request closed without merging**
