### PR TITLE
feat: View all notification page

### PR DESCRIPTION
**Pull request by dhairyathedev**
## Description

- Changed the order of notification to ascending. Latest notification at top.
- Reversed the `requests` array mapping

## Checklist

> Before submitting this pull request, kindly verify that the ensuing checkpoints have been reached.

- [x] Have you adhered to the repository's defined coding convention rules?

Please find the changes, review them and merge the PR.

### CODE REVIEW

**Comment by hereisSwapnil** [comment]
Great job 
@dhairyathedev Can you please limit the number of notes that are visible on the screen so that is looks good on all screen sizes

**Comment by dhairyathedev** [comment]
Hey @hereisSwapnil, do you mean to implement pagination or something like that?

**Comment by hereisSwapnil** [comment]
> Hey @hereisSwapnil, do you mean to implement pagination or something like that?

No limit the notification to 3-4 and view all will redirect you to a notifications page to view all notification
If you implement the view all notifications page, then I can increase your level also

**Comment by dhairyathedev** [comment]
@hereisSwapnil Got it 👍

**Comment by dhairyathedev** [comment]
@hereisSwapnil You can change the level, I am able to create the notification page. #65

**Comment by dhairyathedev** [comment]
Hey @hereisSwapnil, I have added a notification page.

Changes made:
- Add Notification Page path to view all notification
- Limit to 4 notifications in notification card in navbar

Screenshot:
Screenshot 2024-05-11 at 9 28 36 PM


Please review and merge.

**Pull request merged**
