### PR TITLE
added otp feature [ issue #22 solved ]

### PR DESCRIPTION
**Pull request by pspriyanshu601**
## Description

> I have implemented the otp email varification feature(both frontend and backend) in this pull request 
## Checklist

> Before submitting this pull request, kindly verify that the ensuing checkpoints have been reached.

- [x] Have you adhered to the repository's defined coding convention rules?
- [x] Have you updated the 'documentation.md' file with the method/function documentation?
- [x] Have you sent a message along with the result or response?
- [x] Have you used the try-catch technique?
- [x] Has the method/class been added to the documentation (md file)?

## Screenshots

> 

- [ ] 
Screenshot 2024-05-11 at 11 11 38 PM
Screenshot 2024-05-11 at 11 11 22 PM

## Additional Notes/Comments

> Any additional remarks or suggestions concerning this pull request are welcome.

---

I certify that I have carried out the relevant checks and provided the requisite screenshot for validation by submitting this pull request.
I appreciate your contribution.

### CODE REVIEW

**Comment by pspriyanshu601** [comment]
@hereisSwapnil Please review this pull request

**Comment by pspriyanshu601** [comment]
I have added two new environment variables for otp ending email , so please add those before deployment testing .

**Comment by hereisSwapnil** [comment]
@pspriyanshu601 Please resolve conflicts

**Comment by hereisSwapnil** [comment]
@pspriyanshu601 And mention the issue that was assigned to you

**Comment by pspriyanshu601** [comment]
I have resolved the merge conlicts and updated the issue number please review @hereisSwapnil !!

**Comment by hereisSwapnil** [comment]
@pspriyanshu601 Please fix conflicts

**Comment by pspriyanshu601** [comment]
@hereisSwapnil  I have resolved the merge conflicts, some conflicts to .env.dev and .env.sample are coming because we have now new environment variables and those variables are necessary to send the otp so please merge them...

**Comment by hereisSwapnil** [comment]
I cannot merge until you resolve conflicts
image

**Comment by pspriyanshu601** [comment]
resolved all conflicts please merge @hereisSwapnil

**Comment by hereisSwapnil** [comment]
Screenshot from 2024-05-13 18-46-01

This is coming but not redirecting to otp page

**Comment by pspriyanshu601** [comment]
added redirection to otp page @hereisSwapnil , please review .

**Comment by pspriyanshu601** [comment]
> Screenshot from 2024-05-13 18-46-01
> 
> This is coming but not redirecting to otp page

Now added the otp redirection page please review @hereisSwapnil

**Comment by pspriyanshu601** [comment]
Hey @hereisSwapnil please review this again .

**Pull request merged**
