### PR TITLE
added about,privacy,licensing and contact pages

### PR DESCRIPTION
**Pull request by venkatasai24**
## Description

> Added about ,licensing ,privacy and contact us pages..

## Checklist

> Before submitting this pull request, kindly verify that the ensuing checkpoints have been reached.

- [X] Have you adhered to the repository's defined coding convention rules?
- [X] Have you updated the 'documentation.md' file with the method/function documentation?
- [X] Have you sent a message along with the result or response?
- [X] Have you used the try-catch technique?
- [X] Has the method/class been added to the documentation (md file)?

## Screenshots

> Uploading a screenshot illustrating the approach you developed for validation is required.

image
image
image
image

I certify that I have carried out the relevant checks and provided the requisite screenshot for validation by submitting this pull request.
I hope you would love to merge this branch :) ...

### CODE REVIEW

**Comment by hereisSwapnil** [comment]
@venkatasai24 Please resolve conflicts

**Comment by venkatasai24** [comment]
> @venkatasai24 Please resolve conflicts

I did not produce any conflicts like it says some vercel authorization is required, which I won't be able to do it right :(...

**Comment by hereisSwapnil** [comment]
image

@venkatasai24 Resolve this

**Review by venkatasai24 — COMMENTED** [review]
done

**Comment by venkatasai24** [comment]
done :),tq for correcting me @hereisSwapnil  ..

**Comment by venkatasai24** [comment]
done @hereisSwapnil ,I hope you would love to merge this branch..

**Comment by venkatasai24** [comment]
@hereisSwapnil  I request you to review the changes !!

**Pull request closed without merging**
