### PR TITLE
[Feature] : Add search book Results

### PR DESCRIPTION
**Pull request by sivaprasath2004**
## Description
- Hello @hereisSwapnil i have completed the New Feature implemented.
- I will implement the New Feature of the search Results of the books.

## Checklist

> Before submitting this pull request, kindly verify that the ensuing checkpoints have been reached.

- [x] Have you adhered to the repository's defined coding convention rules?
- [x] Have you updated the 'documentation.md' file with the method/function documentation?
- [x] Have you sent a message along with the result or response?
- [x] Have you used the try-catch technique?
- [x] Has the method/class been added to the documentation (md file)?

## Screenshots

[Screencast from 2024-05-15 21-25-53.webm](https://github.com/hereisSwapnil/ExamTime/assets/121082414/14faabe7-69e4-46b3-9181-3d191c8674e4)

### CODE REVIEW

**Comment by hereisSwapnil** [comment]
@sivaprasath2004 Please fix the error in search when I type - "aa"

image

**Comment by sivaprasath2004** [comment]
@hereisSwapnil fixed Is it solved..

**Comment by hereisSwapnil** [comment]
@sivaprasath2004 
This is missing from DocGrid.jsx
  const [dynamicSearch, setDynamicSearch] = useState("");


Also try to remove the query search when the path of the page changes when search button is clicked

**Comment by sivaprasath2004** [comment]
@hereisSwapnil kindly try this time..

**Pull request closed without merging**
