### PR TITLE
-Login/Logout 

### PR DESCRIPTION
**Pull request by CS251000**
## Description

> Smooth transition between register page and login after creating new user. Earlier the login page was not being loaded
>Sign out button working properly

## Checklist

> Before submitting this pull request, kindly verify that the ensuing checkpoints have been reached.

- [ YES] Have you adhered to the repository's defined coding convention rules?
- [YES ] Have you updated the 'documentation.md' file with the method/function documentation?
- [YES ] Have you sent a message along with the result or response?
- [YES ] Have you used the try-catch technique?
- [ YES] Has the method/class been added to the documentation (md file)?

## Screenshots

https://github.com/hereisSwapnil/ExamTime/assets/99918088/b976555c-a361-429c-a495-daf29d1ca04f

https://github.com/hereisSwapnil/ExamTime/assets/99918088/b603685a-3e5b-4008-b8cf-4f4bcd80aba5

---

I certify that I have carried out the relevant checks and provided the requisite screenshot for validation by submitting this pull request.
I appreciate your contribution.

### CODE REVIEW

**Comment by hereisSwapnil** [comment]
@CS251000 After signup, please redirect the user to the homepage as the user will be automatically logged in

**Comment by CS251000** [comment]
https://github.com/hereisSwapnil/ExamTime/assets/99918088/710c1a70-d854-4918-ae3e-d68ad638ea6b

Now signup page directly leads to home page on successful signup

**Comment by hereisSwapnil** [comment]
@CS251000 Please resolve conflicts

**Comment by CS251000** [comment]
@hereisSwapnil kindly check now and tell if it is fine or not

And one more thing, can you kindly tag issue #45 as level 2 instead of level 1 ?

**Comment by hereisSwapnil** [comment]
@CS251000 NO that's not working 

trying this code replacing it with the login function
```
const loginUser = async (data) => {
    setLoading(true);
    axios
      .post(`${import.meta.env.VITE_BASE_URL}/user/login`, data)
      .then((res) => {
        console.log(res.data.message);
        if (res.data.message === "login success") {
          localStorage.setItem("token", res.data.token);
          setUser(res.data.user);
          setloginError("");
          toast.success("Logged in successfully!", {
            position: "top-center",
            autoClose: 5000,
            hideProgressBar: false,
            closeOnClick: false,
            pauseOnHover: false,
            draggable: false,
            progress: undefined,
            theme: "light",
            transition: Bounce,
          });
          navigate("/");
        }
      })
      .catch((err) => {
        if (err.response.data.message === "user not found") {
          setloginError("User not found");
          toast.warning("User not found!", {
            position: "top-center",
            autoClose: 5000,
            hideProgressBar: false,
            closeOnClick: false,
            pauseOnHover: false,
            draggable: false,
            progress: undefined,
            theme: "light",
            transition: Bounce,
          });
        } else if (err.response.data.message === "Invalid credentials") {
          setloginError("Invalid Credentials");
          toast.error("Invalid Credentials!", {
            position: "top-center",
            autoClose: 5000,
            hideProgressBar: false,
            closeOnClick: false,
            pauseOnHover: false,
            draggable: false,
            progress: undefined,
            theme: "light",
            transition: Bounce,
          });
        } else {
          setloginError("Something went wrong!");
          toast.error("An error occurred!", {
            position: "top-center",
            autoClose: 5000,
            hideProgressBar: false,
            closeOnClick: false,
            pauseOnHover: false,
            draggable: false,
            progress: undefined,
            theme: "light",
            transition: Bounce,
          });
        }
      });
    setLoading(false);
  };
```

**Comment by CS251000** [comment]
So you are doing this or what? What do i do now please help

**Comment by hereisSwapnil** [comment]
@CS251000 Change the code and try to push again

**Comment by CS251000** [comment]
@hereisSwapnil check now

**Pull request merged**
